## Feature Engineering

In [13]:
# Import libraries 
import numpy as np 
import pandas as pd 
import scipy as sp 
import os 
import sys
import matplotlib.pyplot as plt

In [14]:
# Setup system configuration for file management
sys.path.append(os.path.join(".."))

## Approach

- Data Ingestion
- Feature Understanding & Analysis
- Feature Selection
- Feature Engineering
- Feature Transformations & Encoding

## Data Ingestion

In [15]:
# Import functionalities to ingest data 
from scripts.data_collection import DataLoader

In [16]:
# Load the dataset
# Instantiate the dataset
dataloader = DataLoader("processed")
dataset = dataloader.collect(filename="laptop_price_ds_v2.csv")
dataset

,Brand,Processor_brand,Processor_name,Processor_gnrtn,Ram_gb,Ram_type,Ssd,Hdd,Os,Os_bit,Graphic_card_gb,Weight,Warranty,Touchscreen,Msoffice,Price,Rating,Number of ratings,Number of reviews
0,ASUS,Intel,Core i3,10th,4,DDR4,512,1024,Windows,64,0,Casual,1,No,No,34649,2,3,0
1,Lenovo,Intel,Core i3,10th,4,DDR4,512,1024,Windows,64,0,Casual,1,No,No,38999,3,65,5
2,Lenovo,Intel,Core i3,10th,4,DDR4,512,1024,Windows,64,0,Casual,1,No,No,39999,3,8,1
3,ASUS,Intel,Core i5,10th,8,DDR4,512,0,Windows,32,2,Casual,1,No,No,69990,3,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4,DDR4,512,512,Windows,64,0,Casual,1,No,No,26990,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,ASUS,AMD,Ryzen 9,Not Available,4,DDR4,1024,0,Windows,64,0,Casual,1,No,No,135990,3,0,0
797,ASUS,AMD,Ryzen 9,Not Available,4,DDR4,1024,0,Windows,64,0,Casual,1,No,No,144990,3,0,0
798,ASUS,AMD,Ryzen 9,Not Available,4,DDR4,1024,0,Windows,64,4,Casual,1,No,No,149990,3,0,0
799,ASUS,AMD,Ryzen 9,Not Available,4,DDR4,1024,0,Windows,64,4,Casual,1,No,No,142990,3,0,0
800,Lenovo,AMD,Ryzen 5,10th,8,DDR4,512,0,DOS,64,0,ThinNlight,1,No,No,57490,4,18,4

## Feature Understanding

In [17]:
# Import libraries for understanding features
from scripts.data_analysis_utils import build_feature_ds
from scripts.data_analysis_utils import build_diagnositc_feature_ds

Idea: create a diagnostic dataframe that presents:
- the feature distribution
- number of distinct values for categorical features

Features with number of distinct values: case studies:
- features less than 3: seperate features
- features less than 10: encoding features

In [18]:
# Check the distribution of feature: Brand
features = dataset.columns
for i, feature in enumerate(features):
    print(f"Feature {i}: {feature}")

Feature 0: Brand
Feature 1: Processor_brand
Feature 2: Processor_name
Feature 3: Processor_gnrtn
Feature 4: Ram_gb
Feature 5: Ram_type
Feature 6: Ssd
Feature 7: Hdd
Feature 8: Os
Feature 9: Os_bit
Feature 10: Graphic_card_gb
Feature 11: Weight
Feature 12: Warranty
Feature 13: Touchscreen
Feature 14: Msoffice
Feature 15: Price
Feature 16: Rating
Feature 17: Number of ratings
Feature 18: Number of reviews

In [19]:
# Understand the distributtion of the feature 
brand_ds = build_feature_ds(dataset,"Brand", "T")
brand_ds

Brand  ASUS  DELL  Lenovo   HP  acer  MSI  APPLE  Avita
count   243   149     144  136    51   49     23      6

In [20]:
# Split the features in categorical and numerical datasets
# Numberical features
feature_num_ds = dataset.select_dtypes([int, float])
feature_num_ds

# Categorical features
feature_cat_ds = dataset.select_dtypes([object])
feature_cat_ds

,Brand,Processor_brand,Processor_name,Processor_gnrtn,Ram_type,Os,Weight,Touchscreen,Msoffice
0,ASUS,Intel,Core i3,10th,DDR4,Windows,Casual,No,No
1,Lenovo,Intel,Core i3,10th,DDR4,Windows,Casual,No,No
2,Lenovo,Intel,Core i3,10th,DDR4,Windows,Casual,No,No
3,ASUS,Intel,Core i5,10th,DDR4,Windows,Casual,No,No
4,ASUS,Intel,Celeron Dual,Not Available,DDR4,Windows,Casual,No,No
...,...,...,...,...,...,...,...,...,...
796,ASUS,AMD,Ryzen 9,Not Available,DDR4,Windows,Casual,No,No
797,ASUS,AMD,Ryzen 9,Not Available,DDR4,Windows,Casual,No,No
798,ASUS,AMD,Ryzen 9,Not Available,DDR4,Windows,Casual,No,No
799,ASUS,AMD,Ryzen 9,Not Available,DDR4,Windows,Casual,No,No
800,Lenovo,AMD,Ryzen 5,10th,DDR4,DOS,ThinNlight,No,No

In [21]:
# Build a diagnostic dataset
diagnostic_ds = build_diagnositc_feature_ds(dataset)
diagnostic_ds

# Save the diagnostic dataset in the correct folder 
diag_data_loader = DataLoader(folder="diagnostics")
diag_data_loader.save(("diagnostics_ds", diagnostic_ds), folder="diagnostics", version_nr=1)
diagnostic_ds

Dataset diagnostics_ds_v1.csv has been stored succesfully in path loc. C:\Development\03_ML_Engineering\Projects\ML_Projects\Laptop_Price_Prediction\data\diagnostics

,FeatureNames,DataTypes,NullValues,NumDistinctValues,UniqueValues
0,Brand,object,0,8,"[ASUS, Lenovo, acer, Avita, HP, DELL, MSI, APPLE]"
1,Processor_brand,object,0,3,"[Intel, AMD, M1]"
2,Processor_name,object,0,11,"[Core i3, Core i5, Celeron Dual, Ryzen 5, Core..."
3,Processor_gnrtn,object,0,8,"[10th, Not Available, 11th, 7th, 8th, 9th, 4th..."
4,Ram_gb,int64,0,4,"[4, 8, 16, 32]"
5,Ram_type,object,0,6,"[DDR4, LPDDR4, LPDDR4X, DDR5, DDR3, LPDDR3]"
6,Ssd,int64,0,6,"[512, 256, 128, 1024, 2048, 3072]"
7,Hdd,int64,0,4,"[1024, 0, 512, 2048]"
8,Os,object,0,3,"[Windows, DOS, Mac]"
9,Os_bit,int64,0,2,"[64, 32]"
10,Graphic_card_gb,int64,0,5,"[0, 2, 4, 6, 8]"
11,Weight,object,0,3,"[Casual, ThinNlight, Gaming]"
12,Warranty,int64,0,3,"[1, 2, 3]"
13,Touchscreen,object,0,2,"[No, Yes]"
14,Msoffice,object,0,2,"[No, Yes]"
15,Price,int64,0,405,"[34649, 38999, 39999, 69990, 26990, 22990, 219..."
16,Rating,int64,0,5,"[2, 3, 4, 5, 1]"
17,Number of ratings,int64,0,282,"[3, 65, 8, 0, 31, 1946, 259, 425, 1120, 286, 5..."
18,Number of reviews,int64,0,135,"[0, 5, 1, 3, 240, 47, 67, 196, 19, 6, 1947, 27..."

## Feature Selection

In [22]:
# Import unilities for selecting features
from scripts.features_utils import FeatureSelector

In [23]:
dataset

,Brand,Processor_brand,Processor_name,Processor_gnrtn,Ram_gb,Ram_type,Ssd,Hdd,Os,Os_bit,Graphic_card_gb,Weight,Warranty,Touchscreen,Msoffice,Price,Rating,Number of ratings,Number of reviews
0,ASUS,Intel,Core i3,10th,4,DDR4,512,1024,Windows,64,0,Casual,1,No,No,34649,2,3,0
1,Lenovo,Intel,Core i3,10th,4,DDR4,512,1024,Windows,64,0,Casual,1,No,No,38999,3,65,5
2,Lenovo,Intel,Core i3,10th,4,DDR4,512,1024,Windows,64,0,Casual,1,No,No,39999,3,8,1
3,ASUS,Intel,Core i5,10th,8,DDR4,512,0,Windows,32,2,Casual,1,No,No,69990,3,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4,DDR4,512,512,Windows,64,0,Casual,1,No,No,26990,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,ASUS,AMD,Ryzen 9,Not Available,4,DDR4,1024,0,Windows,64,0,Casual,1,No,No,135990,3,0,0
797,ASUS,AMD,Ryzen 9,Not Available,4,DDR4,1024,0,Windows,64,0,Casual,1,No,No,144990,3,0,0
798,ASUS,AMD,Ryzen 9,Not Available,4,DDR4,1024,0,Windows,64,4,Casual,1,No,No,149990,3,0,0
799,ASUS,AMD,Ryzen 9,Not Available,4,DDR4,1024,0,Windows,64,4,Casual,1,No,No,142990,3,0,0
800,Lenovo,AMD,Ryzen 5,10th,8,DDR4,512,0,DOS,64,0,ThinNlight,1,No,No,57490,4,18,4

In [24]:
# Exclude a number of features 
# List a number of features to exclude from the dataset
excluded_features = ["Ram_type", "Processor_gnrtn", "Rating",]

# Instatiate a feature selector object to exclude irrelevant features from the dataset
feature_selector = FeatureSelector(dataset)

# Exclude the irrelevant features
dataset1 = feature_selector.exclude(excluded_features)
dataset1

,Brand,Processor_brand,Processor_name,Ram_gb,Ssd,Hdd,Os,Os_bit,Graphic_card_gb,Weight,Warranty,Touchscreen,Msoffice,Price,Number of ratings,Number of reviews
0,ASUS,Intel,Core i3,4,512,1024,Windows,64,0,Casual,1,No,No,34649,3,0
1,Lenovo,Intel,Core i3,4,512,1024,Windows,64,0,Casual,1,No,No,38999,65,5
2,Lenovo,Intel,Core i3,4,512,1024,Windows,64,0,Casual,1,No,No,39999,8,1
3,ASUS,Intel,Core i5,8,512,0,Windows,32,2,Casual,1,No,No,69990,0,0
4,ASUS,Intel,Celeron Dual,4,512,512,Windows,64,0,Casual,1,No,No,26990,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,ASUS,AMD,Ryzen 9,4,1024,0,Windows,64,0,Casual,1,No,No,135990,0,0
797,ASUS,AMD,Ryzen 9,4,1024,0,Windows,64,0,Casual,1,No,No,144990,0,0
798,ASUS,AMD,Ryzen 9,4,1024,0,Windows,64,4,Casual,1,No,No,149990,0,0
799,ASUS,AMD,Ryzen 9,4,1024,0,Windows,64,4,Casual,1,No,No,142990,0,0
800,Lenovo,AMD,Ryzen 5,8,512,0,DOS,64,0,ThinNlight,1,No,No,57490,18,4

In [25]:
# Save the dataset
dataloader.save(("laptop_price_ds", dataset1), folder="processed", version_nr=3)

Dataset laptop_price_ds_v3.csv has been stored succesfully in path loc. C:\Development\03_ML_Engineering\Projects\ML_Projects\Laptop_Price_Prediction\data\processed

## Feature Encoding & Tranformation

In [26]:
# Import functionalities for feature encoding
from scripts.features_utils import FeatureEncoder

**Feature Encoding**: technique to convert categorical values to numerical values
encoding techniques to realise this transformation are:
- Label encoding: technique used for ordinal encoding
- OneHot encoding

**Feature Transformation**: technique to scale up the numerical features to a given range
techniques for feature scaling are:
- data normalization
- min max scaling

### Feature Encoding: Diagnostic Analysis

In [27]:
diagnostic_ds

,FeatureNames,DataTypes,NullValues,NumDistinctValues,UniqueValues
0,Brand,object,0,8,"[ASUS, Lenovo, acer, Avita, HP, DELL, MSI, APPLE]"
1,Processor_brand,object,0,3,"[Intel, AMD, M1]"
2,Processor_name,object,0,11,"[Core i3, Core i5, Celeron Dual, Ryzen 5, Core..."
3,Processor_gnrtn,object,0,8,"[10th, Not Available, 11th, 7th, 8th, 9th, 4th..."
4,Ram_gb,int64,0,4,"[4, 8, 16, 32]"
5,Ram_type,object,0,6,"[DDR4, LPDDR4, LPDDR4X, DDR5, DDR3, LPDDR3]"
6,Ssd,int64,0,6,"[512, 256, 128, 1024, 2048, 3072]"
7,Hdd,int64,0,4,"[1024, 0, 512, 2048]"
8,Os,object,0,3,"[Windows, DOS, Mac]"
9,Os_bit,int64,0,2,"[64, 32]"
10,Graphic_card_gb,int64,0,5,"[0, 2, 4, 6, 8]"
11,Weight,object,0,3,"[Casual, ThinNlight, Gaming]"
12,Warranty,int64,0,3,"[1, 2, 3]"
13,Touchscreen,object,0,2,"[No, Yes]"
14,Msoffice,object,0,2,"[No, Yes]"
15,Price,int64,0,405,"[34649, 38999, 39999, 69990, 26990, 22990, 219..."
16,Rating,int64,0,5,"[2, 3, 4, 5, 1]"
17,Number of ratings,int64,0,282,"[3, 65, 8, 0, 31, 1946, 259, 425, 1120, 286, 5..."
18,Number of reviews,int64,0,135,"[0, 5, 1, 3, 240, 47, 67, 196, 19, 6, 1947, 27..."

**Cardinality**:
- Low: unique values less than 10
- Medium: unique values between 10 and 20
- High: unique values greater than 20

In [28]:
# Function: define the cardinality category
def determine_cardinality_of_func(x: int):
    if x < 10:
        return "Low"
    elif 10<=x<=20:
        return "Medium"
    else:
        return "High"

In [29]:
# Identify features that are ordinal features 
diagnostic_cat_ds = diagnostic_ds[diagnostic_ds["DataTypes"] == object]
diagnostic_cat_ds.loc[:, ["CategoricalType"]] = diagnostic_cat_ds["NumDistinctValues"].apply(lambda x: "Binary" if x == 2 else "Nominal")
diagnostic_cat_ds.index = [i for i in range(diagnostic_cat_ds.shape[0])]

# Define the cardinality of each feature 
diagnostic_cat_ds.loc[:, ["Cardinality"]] = diagnostic_cat_ds["NumDistinctValues"].transform(determine_cardinality_of_func)
diagnostic_cat_ds

,FeatureNames,DataTypes,NullValues,NumDistinctValues,UniqueValues,CategoricalType,Cardinality
0,Brand,object,0,8,"[ASUS, Lenovo, acer, Avita, HP, DELL, MSI, APPLE]",Nominal,Low
1,Processor_brand,object,0,3,"[Intel, AMD, M1]",Nominal,Low
2,Processor_name,object,0,11,"[Core i3, Core i5, Celeron Dual, Ryzen 5, Core...",Nominal,Medium
3,Processor_gnrtn,object,0,8,"[10th, Not Available, 11th, 7th, 8th, 9th, 4th...",Nominal,Low
4,Ram_type,object,0,6,"[DDR4, LPDDR4, LPDDR4X, DDR5, DDR3, LPDDR3]",Nominal,Low
5,Os,object,0,3,"[Windows, DOS, Mac]",Nominal,Low
6,Weight,object,0,3,"[Casual, ThinNlight, Gaming]",Nominal,Low
7,Touchscreen,object,0,2,"[No, Yes]",Binary,Low
8,Msoffice,object,0,2,"[No, Yes]",Binary,Low

- Binary Features: Touchscreen, Msoffice
- Ordinal Features: None
- Nominal Features: all the rest

In [30]:
# Remove the processor generation from the diagnostic dataset
diagnostic_cat_ds = diagnostic_cat_ds.drop(index=[3, 4], axis=0)
diagnostic_cat_ds.index = [idx for idx in range(diagnostic_cat_ds.shape[0])]
diagnostic_cat_ds

# Save the diagnostic data as version 2
diag_data_loader.save(("diagnostic_cat_ds", diagnostic_cat_ds), folder="diagnostics", version_nr=1)

Dataset diagnostic_cat_ds_v1.csv has been stored succesfully in path loc. C:\Development\03_ML_Engineering\Projects\ML_Projects\Laptop_Price_Prediction\data\diagnostics

For nominal features, we use One-Hot Encoding. It is useful to efficiently train as many models there are, such as regression models, knns, svms and tree-based models, like random forest, xgboost models and ligtgbm. The disadventage of OHE technique is it increases the dataset's dimensionality. 

**Solution for reducing dimensionality to preserve all relevant data:**
To reduce the dimensionality of one single dataset, we utilize the normalization technique that take one feature from the dataset and apply onehot encoding. These will provide multiple features, that will be considered to form one dataset. By encoding each feature, the dataset will be stored in a seperate folder called feature_datasets

In [ ]:
dataset1

,Brand,Processor_brand,Processor_name,Ram_gb,Ssd,Hdd,Os,Os_bit,Graphic_card_gb,Weight,Warranty,Touchscreen,Msoffice,Price,Number of ratings,Number of reviews
0,ASUS,Intel,Core i3,4,512,1024,Windows,64,0,Casual,1,No,No,34649,3,0
1,Lenovo,Intel,Core i3,4,512,1024,Windows,64,0,Casual,1,No,No,38999,65,5
2,Lenovo,Intel,Core i3,4,512,1024,Windows,64,0,Casual,1,No,No,39999,8,1
3,ASUS,Intel,Core i5,8,512,0,Windows,32,2,Casual,1,No,No,69990,0,0
4,ASUS,Intel,Celeron Dual,4,512,512,Windows,64,0,Casual,1,No,No,26990,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,ASUS,AMD,Ryzen 9,4,1024,0,Windows,64,0,Casual,1,No,No,135990,0,0
797,ASUS,AMD,Ryzen 9,4,1024,0,Windows,64,0,Casual,1,No,No,144990,0,0
798,ASUS,AMD,Ryzen 9,4,1024,0,Windows,64,4,Casual,1,No,No,149990,0,0
799,ASUS,AMD,Ryzen 9,4,1024,0,Windows,64,4,Casual,1,No,No,142990,0,0
800,Lenovo,AMD,Ryzen 5,8,512,0,DOS,64,0,ThinNlight,1,No,No,57490,18,4

### Feature Encoding: Nominal Features

In [ ]:
# OneHotEncoding
# Initialise the encoding object
# oht_encoder = FeatureEncoder(dataset1, "OneHotEncoding")
# feature_ds1 = oht_encoder.transform("Brand")
# feature_ds1

# Using OneHotEncoding: encode each feature one by one
nominal_feature_names = diagnostic_cat_ds[diagnostic_cat_ds["CategoricalType"] == "Nominal"].loc[:, ["FeatureNames"]].values.transpose()
nominal_feature_names = nominal_feature_names.flatten()

oht_encoder = FeatureEncoder(dataset1, "OneHotEncoding")
folder_loc = oht_encoder.feature_ds_folder_path

for idx, nominal_f_name in enumerate(nominal_feature_names):
    # Encode each feature using OneHotEncoding
    feature_data = oht_encoder.transform(nominal_f_name)

    # Save the encoded feature in the correct folder 
    oht_encoder.save_ds(nominal_f_name, file_idx=idx)
    print(f"Nominal Feature ({nominal_f_name}) is stored successfully in folder loc {folder_loc}")

# Using LabelEncoding:
laben_encoder = FeatureEncoder(dataset1, "OneHotEncoding")
folder_loc = laben_encoder.feature_ds_folder_path

for idx, nominal_f_name in enumerate(nominal_feature_names):
    # Encode each feature using OneHotEncoding
    feature_data = laben_encoder.transform(nominal_f_name)

    # Save the encoded feature in the correct folder 
    laben_encoder.save_ds(nominal_f_name, file_idx=idx)
    print(f"Nominal Feature ({nominal_f_name}) is stored successfully in folder loc {folder_loc}")

Nominal Feature (Brand) is stored successfully in folder loc C:\Development\03_ML_Engineering\Projects\ML_Projects\Laptop_Price_Prediction\data\feature_ds
Nominal Feature (Processor_brand) is stored successfully in folder loc C:\Development\03_ML_Engineering\Projects\ML_Projects\Laptop_Price_Prediction\data\feature_ds
Nominal Feature (Processor_name) is stored successfully in folder loc C:\Development\03_ML_Engineering\Projects\ML_Projects\Laptop_Price_Prediction\data\feature_ds
Nominal Feature (Os) is stored successfully in folder loc C:\Development\03_ML_Engineering\Projects\ML_Projects\Laptop_Price_Prediction\data\feature_ds
Nominal Feature (Weight) is stored successfully in folder loc C:\Development\03_ML_Engineering\Projects\ML_Projects\Laptop_Price_Prediction\data\feature_ds

Finished part 1