# Feature Transformation

In [2]:
# Import libraries
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import os, sys 

# System configuration 
sys.path.append(os.path.abspath(".."))

## FT: Approach

- Data Loading: loading 3 datasets
    - numeric feature dataset v1
    - 2 encoded feature datasets: Processor brand, Weight
- Data Combination: excluding categorical features, combining encoded features only
- Data Storage: storing in the training folder (new)

## Data Loading

In [3]:
# Import dependencies to load the data 
from scripts.data_collection import DataLoader

In [4]:
# Create a dataloader 
enc_data_loader = DataLoader(folder="feature_encoded_ds")
fs_data_loader = DataLoader(folder=r"feature_sel_data\numeric")

# Load the numeric dataset
numeric_ds = fs_data_loader.collect(filename="num_feature_ds_v1.csv")

# Load the 2 encoded dataset
processor_brand_df = enc_data_loader.collect(filename="Processor_name_encoded_ds.csv")
weight_df = enc_data_loader.collect(filename="Weight_encoded_ds.csv")
os_df = enc_data_loader.collect(filename="Os_encoded_ds.csv")

In [5]:
# Numeric dataset
numeric_ds

     Ram_gb   Ssd   Hdd  Graphic_card_gb  Touchscreen   Price
0         4   512  1024                0            0   34649
1         4   512  1024                0            0   38999
2         4   512  1024                0            0   39999
3         8   512     0                2            0   69990
4         4   512   512                0            0   26990
..      ...   ...   ...              ...          ...     ...
796       4  1024     0                0            0  135990
797       4  1024     0                0            0  144990
798       4  1024     0                4            0  149990
799       4  1024     0                4            0  142990
800       8   512     0                0            0   57490

[801 rows x 6 columns]

In [6]:
# Processor Brand data Frame
processor_brand_df

,Processor_name,Celeron Dual,Core i3,Core i5,Core i7,Core i9,M1,Pentium Quad,Ryzen 3,Ryzen 5,Ryzen 7,Ryzen 9
0,Core i3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Core i3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Core i3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Core i5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Celeron Dual,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
796,Ryzen 9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
797,Ryzen 9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
798,Ryzen 9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
799,Ryzen 9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
800,Ryzen 5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [7]:
# Weight DataFrame
weight_df

         Weight  Casual  Gaming  ThinNlight
0        Casual     1.0     0.0         0.0
1        Casual     1.0     0.0         0.0
2        Casual     1.0     0.0         0.0
3        Casual     1.0     0.0         0.0
4        Casual     1.0     0.0         0.0
..          ...     ...     ...         ...
796      Casual     1.0     0.0         0.0
797      Casual     1.0     0.0         0.0
798      Casual     1.0     0.0         0.0
799      Casual     1.0     0.0         0.0
800  ThinNlight     0.0     0.0         1.0

[801 rows x 4 columns]

In [8]:
# Os DataFrame
os_df
os_df.value_counts()

Os       DOS  Mac  Windows
Windows  0.0  0.0  1.0        762
Mac      0.0  1.0  0.0         23
DOS      1.0  0.0  0.0         16
Name: count, dtype: int64

## Data Transformation

In [9]:
# Combine 3 dataset & exclude the number of irrelevant features 
# Processor Brand name: Select the features containing that are Intel (Core) and AMD ("Ryzen") 
processor_brand_names = [brand_name for brand_name in processor_brand_df.columns if ("Core" in brand_name) or ("Ryzen" in brand_name)]
sel_processor_brand_df = processor_brand_df[processor_brand_names]

# Remove the categroical weight feature from the weight df
# weight_df = weight_df.drop(columns=["Weight"]) 

# Extract price feature 
price_feature = numeric_ds[["Price"]]

# Combine the selected processor brand df & weight df and numeric df 
new_feature_ds = pd.concat([numeric_ds, sel_processor_brand_df, weight_df], axis=1)
new_feature_ds = new_feature_ds.drop(columns=["Price"], axis=True)
new_feature_ds = pd.concat([new_feature_ds, price_feature], axis=1)
new_feature_ds

,Ram_gb,Ssd,Hdd,Graphic_card_gb,Touchscreen,Core i3,Core i5,Core i7,Core i9,Ryzen 3,Ryzen 5,Ryzen 7,Ryzen 9,Weight,Casual,Gaming,ThinNlight,Price
0,4,512,1024,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,34649
1,4,512,1024,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,38999
2,4,512,1024,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,39999
3,8,512,0,2,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,69990
4,4,512,512,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,4,1024,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Casual,1.0,0.0,0.0,135990
797,4,1024,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Casual,1.0,0.0,0.0,144990
798,4,1024,0,4,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Casual,1.0,0.0,0.0,149990
799,4,1024,0,4,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Casual,1.0,0.0,0.0,142990
800,8,512,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,ThinNlight,0.0,0.0,1.0,57490

In [10]:
# Add OS feature into the new dataframe
sel_os_features = os_df[["Windows","Mac"]]
new_feature_ds = pd.concat([new_feature_ds, sel_os_features], axis=1)
new_feature_ds

,Ram_gb,Ssd,Hdd,Graphic_card_gb,Touchscreen,Core i3,Core i5,Core i7,Core i9,Ryzen 3,Ryzen 5,Ryzen 7,Ryzen 9,Weight,Casual,Gaming,ThinNlight,Price,Windows,Mac
0,4,512,1024,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,34649,1.0,0.0
1,4,512,1024,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,38999,1.0,0.0
2,4,512,1024,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,39999,1.0,0.0
3,8,512,0,2,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,69990,1.0,0.0
4,4,512,512,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,26990,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,4,1024,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Casual,1.0,0.0,0.0,135990,1.0,0.0
797,4,1024,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Casual,1.0,0.0,0.0,144990,1.0,0.0
798,4,1024,0,4,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Casual,1.0,0.0,0.0,149990,1.0,0.0
799,4,1024,0,4,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Casual,1.0,0.0,0.0,142990,1.0,0.0
800,8,512,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,ThinNlight,0.0,0.0,1.0,57490,0.0,0.0

## Data Storage

In [11]:
new_feature_ds

,Ram_gb,Ssd,Hdd,Graphic_card_gb,Touchscreen,Core i3,Core i5,Core i7,Core i9,Ryzen 3,Ryzen 5,Ryzen 7,Ryzen 9,Weight,Casual,Gaming,ThinNlight,Price,Windows,Mac
0,4,512,1024,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,34649,1.0,0.0
1,4,512,1024,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,38999,1.0,0.0
2,4,512,1024,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,39999,1.0,0.0
3,8,512,0,2,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,69990,1.0,0.0
4,4,512,512,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Casual,1.0,0.0,0.0,26990,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,4,1024,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Casual,1.0,0.0,0.0,135990,1.0,0.0
797,4,1024,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Casual,1.0,0.0,0.0,144990,1.0,0.0
798,4,1024,0,4,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Casual,1.0,0.0,0.0,149990,1.0,0.0
799,4,1024,0,4,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Casual,1.0,0.0,0.0,142990,1.0,0.0
800,8,512,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,ThinNlight,0.0,0.0,1.0,57490,0.0,0.0

In [12]:
# Create a new data saving loader to save new dataset
data_saver = DataLoader(folder="training")
data_saver.save(("data_prepared_set", new_feature_ds), folder="prepared_set", version_nr=1)

Dataset data_prepared_set_v1.csv has been stored succesfully in path loc. C:\Development\03_ML_Engineering\Projects\ML_Projects\Laptop_Price_Prediction\data\training\prepared_set